package club.futurer.community.business.curiosity.dao;

import club.futurer.community.business.curiosity.model.entity.QuestioningVoteSummarizing;
import club.futurer.community.business.curiosity.model.entity.QuestioningVoteSummarizingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestioningVoteSummarizingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    long countByExample(QuestioningVoteSummarizingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int insert(QuestioningVoteSummarizing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int insertSelective(QuestioningVoteSummarizing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    List<QuestioningVoteSummarizing> selectByExample(QuestioningVoteSummarizingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    QuestioningVoteSummarizing selectByPrimaryKey(Long questioningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestioningVoteSummarizing record, @Param("example") QuestioningVoteSummarizingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestioningVoteSummarizing record, @Param("example") QuestioningVoteSummarizingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestioningVoteSummarizing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote_summarizing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestioningVoteSummarizing record);
}