package club.futurer.community.business.curiosity.dao;

import club.futurer.community.business.curiosity.model.entity.QuestioningScore;
import club.futurer.community.business.curiosity.model.entity.QuestioningScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestioningScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    long countByExample(QuestioningScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int insert(QuestioningScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int insertSelective(QuestioningScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    List<QuestioningScore> selectByExample(QuestioningScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    QuestioningScore selectByPrimaryKey(Long questioningId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestioningScore record, @Param("example") QuestioningScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestioningScore record, @Param("example") QuestioningScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestioningScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestioningScore record);
}