package club.futurer.community.business.curiosity.dao;

import club.futurer.community.business.curiosity.model.entity.QuestioningCommentScore;
import club.futurer.community.business.curiosity.model.entity.QuestioningCommentScoreExample;
import club.futurer.community.business.curiosity.model.entity.QuestioningCommentScoreKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestioningCommentScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    long countByExample(QuestioningCommentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int insert(QuestioningCommentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int insertSelective(QuestioningCommentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    List<QuestioningCommentScore> selectByExample(QuestioningCommentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    QuestioningCommentScore selectByPrimaryKey(QuestioningCommentScoreKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestioningCommentScore record, @Param("example") QuestioningCommentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestioningCommentScore record, @Param("example") QuestioningCommentScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestioningCommentScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestioningCommentScore record);
}