package club.futurer.community.business.curiosity.dao;

import club.futurer.community.business.curiosity.model.entity.QuestioningComment;
import club.futurer.community.business.curiosity.model.entity.QuestioningCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestioningCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    long countByExample(QuestioningCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int insert(QuestioningComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int insertSelective(QuestioningComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    List<QuestioningComment> selectByExample(QuestioningCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    QuestioningComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestioningComment record, @Param("example") QuestioningCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestioningComment record, @Param("example") QuestioningCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuestioningComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuestioningComment record);
}