package club.futurer.community.business.curiosity.model.entity;

import java.util.Date;

public class Questioning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.author_name
     *
     * @mbg.generated
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.author_userid
     *
     * @mbg.generated
     */
    private Long authorUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.author_identityid
     *
     * @mbg.generated
     */
    private String authorIdentityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.publish_time
     *
     * @mbg.generated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.oper_time
     *
     * @mbg.generated
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.contract_address
     *
     * @mbg.generated
     */
    private String contractAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning.md_content
     *
     * @mbg.generated
     */
    private String mdContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.id
     *
     * @return the value of questioning.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.id
     *
     * @param id the value for questioning.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.questioning_id
     *
     * @return the value of questioning.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.questioning_id
     *
     * @param questioningId the value for questioning.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.content
     *
     * @return the value of questioning.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.content
     *
     * @param content the value for questioning.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.hash
     *
     * @return the value of questioning.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.hash
     *
     * @param hash the value for questioning.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.author_name
     *
     * @return the value of questioning.author_name
     *
     * @mbg.generated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.author_name
     *
     * @param authorName the value for questioning.author_name
     *
     * @mbg.generated
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName == null ? null : authorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.author_userid
     *
     * @return the value of questioning.author_userid
     *
     * @mbg.generated
     */
    public Long getAuthorUserid() {
        return authorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.author_userid
     *
     * @param authorUserid the value for questioning.author_userid
     *
     * @mbg.generated
     */
    public void setAuthorUserid(Long authorUserid) {
        this.authorUserid = authorUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.author_identityid
     *
     * @return the value of questioning.author_identityid
     *
     * @mbg.generated
     */
    public String getAuthorIdentityid() {
        return authorIdentityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.author_identityid
     *
     * @param authorIdentityid the value for questioning.author_identityid
     *
     * @mbg.generated
     */
    public void setAuthorIdentityid(String authorIdentityid) {
        this.authorIdentityid = authorIdentityid == null ? null : authorIdentityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.publish_time
     *
     * @return the value of questioning.publish_time
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.publish_time
     *
     * @param publishTime the value for questioning.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.oper_time
     *
     * @return the value of questioning.oper_time
     *
     * @mbg.generated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.oper_time
     *
     * @param operTime the value for questioning.oper_time
     *
     * @mbg.generated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.version
     *
     * @return the value of questioning.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.version
     *
     * @param version the value for questioning.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.tags
     *
     * @return the value of questioning.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.tags
     *
     * @param tags the value for questioning.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.contract_address
     *
     * @return the value of questioning.contract_address
     *
     * @mbg.generated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.contract_address
     *
     * @param contractAddress the value for questioning.contract_address
     *
     * @mbg.generated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.summary
     *
     * @return the value of questioning.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.summary
     *
     * @param summary the value for questioning.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.signature
     *
     * @return the value of questioning.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.signature
     *
     * @param signature the value for questioning.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.images
     *
     * @return the value of questioning.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.images
     *
     * @param images the value for questioning.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning.md_content
     *
     * @return the value of questioning.md_content
     *
     * @mbg.generated
     */
    public String getMdContent() {
        return mdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning.md_content
     *
     * @param mdContent the value for questioning.md_content
     *
     * @mbg.generated
     */
    public void setMdContent(String mdContent) {
        this.mdContent = mdContent == null ? null : mdContent.trim();
    }
}