package club.futurer.community.business.curiosity.model.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuestioningVoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public QuestioningVoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestioningIdIsNull() {
            addCriterion("questioning_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdIsNotNull() {
            addCriterion("questioning_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdEqualTo(Long value) {
            addCriterion("questioning_id =", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdNotEqualTo(Long value) {
            addCriterion("questioning_id <>", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdGreaterThan(Long value) {
            addCriterion("questioning_id >", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdGreaterThanOrEqualTo(Long value) {
            addCriterion("questioning_id >=", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdLessThan(Long value) {
            addCriterion("questioning_id <", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdLessThanOrEqualTo(Long value) {
            addCriterion("questioning_id <=", value, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdIn(List<Long> values) {
            addCriterion("questioning_id in", values, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdNotIn(List<Long> values) {
            addCriterion("questioning_id not in", values, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdBetween(Long value1, Long value2) {
            addCriterion("questioning_id between", value1, value2, "questioningId");
            return (Criteria) this;
        }

        public Criteria andQuestioningIdNotBetween(Long value1, Long value2) {
            addCriterion("questioning_id not between", value1, value2, "questioningId");
            return (Criteria) this;
        }

        public Criteria andVoteUseridIsNull() {
            addCriterion("vote_userid is null");
            return (Criteria) this;
        }

        public Criteria andVoteUseridIsNotNull() {
            addCriterion("vote_userid is not null");
            return (Criteria) this;
        }

        public Criteria andVoteUseridEqualTo(Long value) {
            addCriterion("vote_userid =", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridNotEqualTo(Long value) {
            addCriterion("vote_userid <>", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridGreaterThan(Long value) {
            addCriterion("vote_userid >", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("vote_userid >=", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridLessThan(Long value) {
            addCriterion("vote_userid <", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridLessThanOrEqualTo(Long value) {
            addCriterion("vote_userid <=", value, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridIn(List<Long> values) {
            addCriterion("vote_userid in", values, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridNotIn(List<Long> values) {
            addCriterion("vote_userid not in", values, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridBetween(Long value1, Long value2) {
            addCriterion("vote_userid between", value1, value2, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteUseridNotBetween(Long value1, Long value2) {
            addCriterion("vote_userid not between", value1, value2, "voteUserid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidIsNull() {
            addCriterion("vote_identityid is null");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidIsNotNull() {
            addCriterion("vote_identityid is not null");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidEqualTo(String value) {
            addCriterion("vote_identityid =", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidNotEqualTo(String value) {
            addCriterion("vote_identityid <>", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidGreaterThan(String value) {
            addCriterion("vote_identityid >", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidGreaterThanOrEqualTo(String value) {
            addCriterion("vote_identityid >=", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidLessThan(String value) {
            addCriterion("vote_identityid <", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidLessThanOrEqualTo(String value) {
            addCriterion("vote_identityid <=", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidLike(String value) {
            addCriterion("vote_identityid like", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidNotLike(String value) {
            addCriterion("vote_identityid not like", value, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidIn(List<String> values) {
            addCriterion("vote_identityid in", values, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidNotIn(List<String> values) {
            addCriterion("vote_identityid not in", values, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidBetween(String value1, String value2) {
            addCriterion("vote_identityid between", value1, value2, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteIdentityidNotBetween(String value1, String value2) {
            addCriterion("vote_identityid not between", value1, value2, "voteIdentityid");
            return (Criteria) this;
        }

        public Criteria andVoteTypeIsNull() {
            addCriterion("vote_type is null");
            return (Criteria) this;
        }

        public Criteria andVoteTypeIsNotNull() {
            addCriterion("vote_type is not null");
            return (Criteria) this;
        }

        public Criteria andVoteTypeEqualTo(Integer value) {
            addCriterion("vote_type =", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeNotEqualTo(Integer value) {
            addCriterion("vote_type <>", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeGreaterThan(Integer value) {
            addCriterion("vote_type >", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("vote_type >=", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeLessThan(Integer value) {
            addCriterion("vote_type <", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeLessThanOrEqualTo(Integer value) {
            addCriterion("vote_type <=", value, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeIn(List<Integer> values) {
            addCriterion("vote_type in", values, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeNotIn(List<Integer> values) {
            addCriterion("vote_type not in", values, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeBetween(Integer value1, Integer value2) {
            addCriterion("vote_type between", value1, value2, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("vote_type not between", value1, value2, "voteType");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIsNull() {
            addCriterion("vote_time is null");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIsNotNull() {
            addCriterion("vote_time is not null");
            return (Criteria) this;
        }

        public Criteria andVoteTimeEqualTo(Date value) {
            addCriterion("vote_time =", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotEqualTo(Date value) {
            addCriterion("vote_time <>", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeGreaterThan(Date value) {
            addCriterion("vote_time >", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("vote_time >=", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeLessThan(Date value) {
            addCriterion("vote_time <", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeLessThanOrEqualTo(Date value) {
            addCriterion("vote_time <=", value, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeIn(List<Date> values) {
            addCriterion("vote_time in", values, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotIn(List<Date> values) {
            addCriterion("vote_time not in", values, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeBetween(Date value1, Date value2) {
            addCriterion("vote_time between", value1, value2, "voteTime");
            return (Criteria) this;
        }

        public Criteria andVoteTimeNotBetween(Date value1, Date value2) {
            addCriterion("vote_time not between", value1, value2, "voteTime");
            return (Criteria) this;
        }

        public Criteria andOnChainIsNull() {
            addCriterion("on_chain is null");
            return (Criteria) this;
        }

        public Criteria andOnChainIsNotNull() {
            addCriterion("on_chain is not null");
            return (Criteria) this;
        }

        public Criteria andOnChainEqualTo(Boolean value) {
            addCriterion("on_chain =", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainNotEqualTo(Boolean value) {
            addCriterion("on_chain <>", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainGreaterThan(Boolean value) {
            addCriterion("on_chain >", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainGreaterThanOrEqualTo(Boolean value) {
            addCriterion("on_chain >=", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainLessThan(Boolean value) {
            addCriterion("on_chain <", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainLessThanOrEqualTo(Boolean value) {
            addCriterion("on_chain <=", value, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainIn(List<Boolean> values) {
            addCriterion("on_chain in", values, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainNotIn(List<Boolean> values) {
            addCriterion("on_chain not in", values, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainBetween(Boolean value1, Boolean value2) {
            addCriterion("on_chain between", value1, value2, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainNotBetween(Boolean value1, Boolean value2) {
            addCriterion("on_chain not between", value1, value2, "onChain");
            return (Criteria) this;
        }

        public Criteria andOnChainProofIsNull() {
            addCriterion("on_chain_proof is null");
            return (Criteria) this;
        }

        public Criteria andOnChainProofIsNotNull() {
            addCriterion("on_chain_proof is not null");
            return (Criteria) this;
        }

        public Criteria andOnChainProofEqualTo(String value) {
            addCriterion("on_chain_proof =", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofNotEqualTo(String value) {
            addCriterion("on_chain_proof <>", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofGreaterThan(String value) {
            addCriterion("on_chain_proof >", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofGreaterThanOrEqualTo(String value) {
            addCriterion("on_chain_proof >=", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofLessThan(String value) {
            addCriterion("on_chain_proof <", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofLessThanOrEqualTo(String value) {
            addCriterion("on_chain_proof <=", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofLike(String value) {
            addCriterion("on_chain_proof like", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofNotLike(String value) {
            addCriterion("on_chain_proof not like", value, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofIn(List<String> values) {
            addCriterion("on_chain_proof in", values, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofNotIn(List<String> values) {
            addCriterion("on_chain_proof not in", values, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofBetween(String value1, String value2) {
            addCriterion("on_chain_proof between", value1, value2, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andOnChainProofNotBetween(String value1, String value2) {
            addCriterion("on_chain_proof not between", value1, value2, "onChainProof");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("signature not between", value1, value2, "signature");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioning_vote
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table questioning_vote
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}