package club.futurer.community.business.curiosity.model.entity;

import java.util.Date;

public class QuestioningVote extends QuestioningVoteKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.vote_identityid
     *
     * @mbg.generated
     */
    private String voteIdentityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.vote_type
     *
     * @mbg.generated
     */
    private Integer voteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.vote_time
     *
     * @mbg.generated
     */
    private Date voteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.on_chain
     *
     * @mbg.generated
     */
    private Boolean onChain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.on_chain_proof
     *
     * @mbg.generated
     */
    private String onChainProof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.vote_identityid
     *
     * @return the value of questioning_vote.vote_identityid
     *
     * @mbg.generated
     */
    public String getVoteIdentityid() {
        return voteIdentityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.vote_identityid
     *
     * @param voteIdentityid the value for questioning_vote.vote_identityid
     *
     * @mbg.generated
     */
    public void setVoteIdentityid(String voteIdentityid) {
        this.voteIdentityid = voteIdentityid == null ? null : voteIdentityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.vote_type
     *
     * @return the value of questioning_vote.vote_type
     *
     * @mbg.generated
     */
    public Integer getVoteType() {
        return voteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.vote_type
     *
     * @param voteType the value for questioning_vote.vote_type
     *
     * @mbg.generated
     */
    public void setVoteType(Integer voteType) {
        this.voteType = voteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.vote_time
     *
     * @return the value of questioning_vote.vote_time
     *
     * @mbg.generated
     */
    public Date getVoteTime() {
        return voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.vote_time
     *
     * @param voteTime the value for questioning_vote.vote_time
     *
     * @mbg.generated
     */
    public void setVoteTime(Date voteTime) {
        this.voteTime = voteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.on_chain
     *
     * @return the value of questioning_vote.on_chain
     *
     * @mbg.generated
     */
    public Boolean getOnChain() {
        return onChain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.on_chain
     *
     * @param onChain the value for questioning_vote.on_chain
     *
     * @mbg.generated
     */
    public void setOnChain(Boolean onChain) {
        this.onChain = onChain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.on_chain_proof
     *
     * @return the value of questioning_vote.on_chain_proof
     *
     * @mbg.generated
     */
    public String getOnChainProof() {
        return onChainProof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.on_chain_proof
     *
     * @param onChainProof the value for questioning_vote.on_chain_proof
     *
     * @mbg.generated
     */
    public void setOnChainProof(String onChainProof) {
        this.onChainProof = onChainProof == null ? null : onChainProof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.signature
     *
     * @return the value of questioning_vote.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.signature
     *
     * @param signature the value for questioning_vote.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }
}