package club.futurer.community.business.curiosity.model.entity;

public class QuestioningVoteKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote.vote_userid
     *
     * @mbg.generated
     */
    private Long voteUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.questioning_id
     *
     * @return the value of questioning_vote.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.questioning_id
     *
     * @param questioningId the value for questioning_vote.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote.vote_userid
     *
     * @return the value of questioning_vote.vote_userid
     *
     * @mbg.generated
     */
    public Long getVoteUserid() {
        return voteUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote.vote_userid
     *
     * @param voteUserid the value for questioning_vote.vote_userid
     *
     * @mbg.generated
     */
    public void setVoteUserid(Long voteUserid) {
        this.voteUserid = voteUserid;
    }
}