package club.futurer.community.business.curiosity.model.entity;

import java.util.Date;

public class QuestioningComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_name
     *
     * @mbg.generated
     */
    private String commentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_userid
     *
     * @mbg.generated
     */
    private Long commentUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_identityid
     *
     * @mbg.generated
     */
    private String commentIdentityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_time
     *
     * @mbg.generated
     */
    private Date commentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_type
     *
     * @mbg.generated
     */
    private Integer commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.up_count
     *
     * @mbg.generated
     */
    private Long upCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.down_count
     *
     * @mbg.generated
     */
    private Long downCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.comment_count
     *
     * @mbg.generated
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.parent_id
     *
     * @mbg.generated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.oper_time
     *
     * @mbg.generated
     */
    private Date operTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.hash
     *
     * @mbg.generated
     */
    private String hash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.tags
     *
     * @mbg.generated
     */
    private String tags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.on_chain
     *
     * @mbg.generated
     */
    private Boolean onChain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.on_chain_proof
     *
     * @mbg.generated
     */
    private String onChainProof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.signature
     *
     * @mbg.generated
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment.md_content
     *
     * @mbg.generated
     */
    private String mdContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.id
     *
     * @return the value of questioning_comment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.id
     *
     * @param id the value for questioning_comment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_name
     *
     * @return the value of questioning_comment.comment_name
     *
     * @mbg.generated
     */
    public String getCommentName() {
        return commentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_name
     *
     * @param commentName the value for questioning_comment.comment_name
     *
     * @mbg.generated
     */
    public void setCommentName(String commentName) {
        this.commentName = commentName == null ? null : commentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_userid
     *
     * @return the value of questioning_comment.comment_userid
     *
     * @mbg.generated
     */
    public Long getCommentUserid() {
        return commentUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_userid
     *
     * @param commentUserid the value for questioning_comment.comment_userid
     *
     * @mbg.generated
     */
    public void setCommentUserid(Long commentUserid) {
        this.commentUserid = commentUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_identityid
     *
     * @return the value of questioning_comment.comment_identityid
     *
     * @mbg.generated
     */
    public String getCommentIdentityid() {
        return commentIdentityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_identityid
     *
     * @param commentIdentityid the value for questioning_comment.comment_identityid
     *
     * @mbg.generated
     */
    public void setCommentIdentityid(String commentIdentityid) {
        this.commentIdentityid = commentIdentityid == null ? null : commentIdentityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_time
     *
     * @return the value of questioning_comment.comment_time
     *
     * @mbg.generated
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_time
     *
     * @param commentTime the value for questioning_comment.comment_time
     *
     * @mbg.generated
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.content
     *
     * @return the value of questioning_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.content
     *
     * @param content the value for questioning_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_type
     *
     * @return the value of questioning_comment.comment_type
     *
     * @mbg.generated
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_type
     *
     * @param commentType the value for questioning_comment.comment_type
     *
     * @mbg.generated
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.up_count
     *
     * @return the value of questioning_comment.up_count
     *
     * @mbg.generated
     */
    public Long getUpCount() {
        return upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.up_count
     *
     * @param upCount the value for questioning_comment.up_count
     *
     * @mbg.generated
     */
    public void setUpCount(Long upCount) {
        this.upCount = upCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.down_count
     *
     * @return the value of questioning_comment.down_count
     *
     * @mbg.generated
     */
    public Long getDownCount() {
        return downCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.down_count
     *
     * @param downCount the value for questioning_comment.down_count
     *
     * @mbg.generated
     */
    public void setDownCount(Long downCount) {
        this.downCount = downCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.comment_count
     *
     * @return the value of questioning_comment.comment_count
     *
     * @mbg.generated
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.comment_count
     *
     * @param commentCount the value for questioning_comment.comment_count
     *
     * @mbg.generated
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.questioning_id
     *
     * @return the value of questioning_comment.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.questioning_id
     *
     * @param questioningId the value for questioning_comment.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.parent_id
     *
     * @return the value of questioning_comment.parent_id
     *
     * @mbg.generated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.parent_id
     *
     * @param parentId the value for questioning_comment.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.oper_time
     *
     * @return the value of questioning_comment.oper_time
     *
     * @mbg.generated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.oper_time
     *
     * @param operTime the value for questioning_comment.oper_time
     *
     * @mbg.generated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.version
     *
     * @return the value of questioning_comment.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.version
     *
     * @param version the value for questioning_comment.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.hash
     *
     * @return the value of questioning_comment.hash
     *
     * @mbg.generated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.hash
     *
     * @param hash the value for questioning_comment.hash
     *
     * @mbg.generated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.tags
     *
     * @return the value of questioning_comment.tags
     *
     * @mbg.generated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.tags
     *
     * @param tags the value for questioning_comment.tags
     *
     * @mbg.generated
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.summary
     *
     * @return the value of questioning_comment.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.summary
     *
     * @param summary the value for questioning_comment.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.on_chain
     *
     * @return the value of questioning_comment.on_chain
     *
     * @mbg.generated
     */
    public Boolean getOnChain() {
        return onChain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.on_chain
     *
     * @param onChain the value for questioning_comment.on_chain
     *
     * @mbg.generated
     */
    public void setOnChain(Boolean onChain) {
        this.onChain = onChain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.on_chain_proof
     *
     * @return the value of questioning_comment.on_chain_proof
     *
     * @mbg.generated
     */
    public String getOnChainProof() {
        return onChainProof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.on_chain_proof
     *
     * @param onChainProof the value for questioning_comment.on_chain_proof
     *
     * @mbg.generated
     */
    public void setOnChainProof(String onChainProof) {
        this.onChainProof = onChainProof == null ? null : onChainProof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.signature
     *
     * @return the value of questioning_comment.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.signature
     *
     * @param signature the value for questioning_comment.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.images
     *
     * @return the value of questioning_comment.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.images
     *
     * @param images the value for questioning_comment.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment.md_content
     *
     * @return the value of questioning_comment.md_content
     *
     * @mbg.generated
     */
    public String getMdContent() {
        return mdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment.md_content
     *
     * @param mdContent the value for questioning_comment.md_content
     *
     * @mbg.generated
     */
    public void setMdContent(String mdContent) {
        this.mdContent = mdContent == null ? null : mdContent.trim();
    }
}