package club.futurer.community.business.curiosity.model.entity;

import java.math.BigDecimal;

public class QuestioningScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.hacker_news_score
     *
     * @mbg.generated
     */
    private BigDecimal hackerNewsScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.reddit_score
     *
     * @mbg.generated
     */
    private BigDecimal redditScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.stackoverflow_score
     *
     * @mbg.generated
     */
    private BigDecimal stackoverflowScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.newton_cooling_score
     *
     * @mbg.generated
     */
    private BigDecimal newtonCoolingScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.wilson_score
     *
     * @mbg.generated
     */
    private BigDecimal wilsonScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_score.bayesian_average_score
     *
     * @mbg.generated
     */
    private BigDecimal bayesianAverageScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.questioning_id
     *
     * @return the value of questioning_score.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.questioning_id
     *
     * @param questioningId the value for questioning_score.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.hacker_news_score
     *
     * @return the value of questioning_score.hacker_news_score
     *
     * @mbg.generated
     */
    public BigDecimal getHackerNewsScore() {
        return hackerNewsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.hacker_news_score
     *
     * @param hackerNewsScore the value for questioning_score.hacker_news_score
     *
     * @mbg.generated
     */
    public void setHackerNewsScore(BigDecimal hackerNewsScore) {
        this.hackerNewsScore = hackerNewsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.reddit_score
     *
     * @return the value of questioning_score.reddit_score
     *
     * @mbg.generated
     */
    public BigDecimal getRedditScore() {
        return redditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.reddit_score
     *
     * @param redditScore the value for questioning_score.reddit_score
     *
     * @mbg.generated
     */
    public void setRedditScore(BigDecimal redditScore) {
        this.redditScore = redditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.stackoverflow_score
     *
     * @return the value of questioning_score.stackoverflow_score
     *
     * @mbg.generated
     */
    public BigDecimal getStackoverflowScore() {
        return stackoverflowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.stackoverflow_score
     *
     * @param stackoverflowScore the value for questioning_score.stackoverflow_score
     *
     * @mbg.generated
     */
    public void setStackoverflowScore(BigDecimal stackoverflowScore) {
        this.stackoverflowScore = stackoverflowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.newton_cooling_score
     *
     * @return the value of questioning_score.newton_cooling_score
     *
     * @mbg.generated
     */
    public BigDecimal getNewtonCoolingScore() {
        return newtonCoolingScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.newton_cooling_score
     *
     * @param newtonCoolingScore the value for questioning_score.newton_cooling_score
     *
     * @mbg.generated
     */
    public void setNewtonCoolingScore(BigDecimal newtonCoolingScore) {
        this.newtonCoolingScore = newtonCoolingScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.wilson_score
     *
     * @return the value of questioning_score.wilson_score
     *
     * @mbg.generated
     */
    public BigDecimal getWilsonScore() {
        return wilsonScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.wilson_score
     *
     * @param wilsonScore the value for questioning_score.wilson_score
     *
     * @mbg.generated
     */
    public void setWilsonScore(BigDecimal wilsonScore) {
        this.wilsonScore = wilsonScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_score.bayesian_average_score
     *
     * @return the value of questioning_score.bayesian_average_score
     *
     * @mbg.generated
     */
    public BigDecimal getBayesianAverageScore() {
        return bayesianAverageScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_score.bayesian_average_score
     *
     * @param bayesianAverageScore the value for questioning_score.bayesian_average_score
     *
     * @mbg.generated
     */
    public void setBayesianAverageScore(BigDecimal bayesianAverageScore) {
        this.bayesianAverageScore = bayesianAverageScore;
    }
}