package club.futurer.community.business.curiosity.model.entity;

public class QuestioningVoteSummarizing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.percent191
     *
     * @mbg.generated
     */
    private Integer percent191;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.percent382
     *
     * @mbg.generated
     */
    private Integer percent382;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.percent500
     *
     * @mbg.generated
     */
    private Integer percent500;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.percent618
     *
     * @mbg.generated
     */
    private Integer percent618;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.percent809
     *
     * @mbg.generated
     */
    private Integer percent809;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_vote_summarizing.excellent
     *
     * @mbg.generated
     */
    private Integer excellent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.questioning_id
     *
     * @return the value of questioning_vote_summarizing.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.questioning_id
     *
     * @param questioningId the value for questioning_vote_summarizing.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.percent191
     *
     * @return the value of questioning_vote_summarizing.percent191
     *
     * @mbg.generated
     */
    public Integer getPercent191() {
        return percent191;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.percent191
     *
     * @param percent191 the value for questioning_vote_summarizing.percent191
     *
     * @mbg.generated
     */
    public void setPercent191(Integer percent191) {
        this.percent191 = percent191;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.percent382
     *
     * @return the value of questioning_vote_summarizing.percent382
     *
     * @mbg.generated
     */
    public Integer getPercent382() {
        return percent382;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.percent382
     *
     * @param percent382 the value for questioning_vote_summarizing.percent382
     *
     * @mbg.generated
     */
    public void setPercent382(Integer percent382) {
        this.percent382 = percent382;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.percent500
     *
     * @return the value of questioning_vote_summarizing.percent500
     *
     * @mbg.generated
     */
    public Integer getPercent500() {
        return percent500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.percent500
     *
     * @param percent500 the value for questioning_vote_summarizing.percent500
     *
     * @mbg.generated
     */
    public void setPercent500(Integer percent500) {
        this.percent500 = percent500;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.percent618
     *
     * @return the value of questioning_vote_summarizing.percent618
     *
     * @mbg.generated
     */
    public Integer getPercent618() {
        return percent618;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.percent618
     *
     * @param percent618 the value for questioning_vote_summarizing.percent618
     *
     * @mbg.generated
     */
    public void setPercent618(Integer percent618) {
        this.percent618 = percent618;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.percent809
     *
     * @return the value of questioning_vote_summarizing.percent809
     *
     * @mbg.generated
     */
    public Integer getPercent809() {
        return percent809;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.percent809
     *
     * @param percent809 the value for questioning_vote_summarizing.percent809
     *
     * @mbg.generated
     */
    public void setPercent809(Integer percent809) {
        this.percent809 = percent809;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_vote_summarizing.excellent
     *
     * @return the value of questioning_vote_summarizing.excellent
     *
     * @mbg.generated
     */
    public Integer getExcellent() {
        return excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_vote_summarizing.excellent
     *
     * @param excellent the value for questioning_vote_summarizing.excellent
     *
     * @mbg.generated
     */
    public void setExcellent(Integer excellent) {
        this.excellent = excellent;
    }
}