package club.futurer.community.business.curiosity.model.entity;

public class QuestioningCommentScoreKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment_score.questioning_comment_id
     *
     * @mbg.generated
     */
    private Long questioningCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questioning_comment_score.questioning_id
     *
     * @mbg.generated
     */
    private Long questioningId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment_score.questioning_comment_id
     *
     * @return the value of questioning_comment_score.questioning_comment_id
     *
     * @mbg.generated
     */
    public Long getQuestioningCommentId() {
        return questioningCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment_score.questioning_comment_id
     *
     * @param questioningCommentId the value for questioning_comment_score.questioning_comment_id
     *
     * @mbg.generated
     */
    public void setQuestioningCommentId(Long questioningCommentId) {
        this.questioningCommentId = questioningCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questioning_comment_score.questioning_id
     *
     * @return the value of questioning_comment_score.questioning_id
     *
     * @mbg.generated
     */
    public Long getQuestioningId() {
        return questioningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questioning_comment_score.questioning_id
     *
     * @param questioningId the value for questioning_comment_score.questioning_id
     *
     * @mbg.generated
     */
    public void setQuestioningId(Long questioningId) {
        this.questioningId = questioningId;
    }
}