package club.futurer.community.business.user.model.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity_id
     *
     * @mbg.generated
     */
    private String identityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity_key_pair
     *
     * @mbg.generated
     */
    private String identityKeyPair;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.signed_pre_key
     *
     * @mbg.generated
     */
    private String signedPreKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.one_time_pre_keys
     *
     * @mbg.generated
     */
    private String oneTimePreKeys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ephemeral_key
     *
     * @mbg.generated
     */
    private String ephemeralKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.grade
     *
     * @mbg.generated
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity_id
     *
     * @return the value of user.identity_id
     *
     * @mbg.generated
     */
    public String getIdentityId() {
        return identityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity_id
     *
     * @param identityId the value for user.identity_id
     *
     * @mbg.generated
     */
    public void setIdentityId(String identityId) {
        this.identityId = identityId == null ? null : identityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity_key_pair
     *
     * @return the value of user.identity_key_pair
     *
     * @mbg.generated
     */
    public String getIdentityKeyPair() {
        return identityKeyPair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity_key_pair
     *
     * @param identityKeyPair the value for user.identity_key_pair
     *
     * @mbg.generated
     */
    public void setIdentityKeyPair(String identityKeyPair) {
        this.identityKeyPair = identityKeyPair == null ? null : identityKeyPair.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.signed_pre_key
     *
     * @return the value of user.signed_pre_key
     *
     * @mbg.generated
     */
    public String getSignedPreKey() {
        return signedPreKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.signed_pre_key
     *
     * @param signedPreKey the value for user.signed_pre_key
     *
     * @mbg.generated
     */
    public void setSignedPreKey(String signedPreKey) {
        this.signedPreKey = signedPreKey == null ? null : signedPreKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.one_time_pre_keys
     *
     * @return the value of user.one_time_pre_keys
     *
     * @mbg.generated
     */
    public String getOneTimePreKeys() {
        return oneTimePreKeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.one_time_pre_keys
     *
     * @param oneTimePreKeys the value for user.one_time_pre_keys
     *
     * @mbg.generated
     */
    public void setOneTimePreKeys(String oneTimePreKeys) {
        this.oneTimePreKeys = oneTimePreKeys == null ? null : oneTimePreKeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ephemeral_key
     *
     * @return the value of user.ephemeral_key
     *
     * @mbg.generated
     */
    public String getEphemeralKey() {
        return ephemeralKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ephemeral_key
     *
     * @param ephemeralKey the value for user.ephemeral_key
     *
     * @mbg.generated
     */
    public void setEphemeralKey(String ephemeralKey) {
        this.ephemeralKey = ephemeralKey == null ? null : ephemeralKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created
     *
     * @return the value of user.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created
     *
     * @param created the value for user.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.grade
     *
     * @return the value of user.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.grade
     *
     * @param grade the value for user.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}